04-02-2020 15:09:23.762 [main] DEBUG o.s.web.context.ContextLoader.prepareWebApplicationContext - Published root WebApplicationContext as ServletContext attribute with name [org.springframework.web.context.WebApplicationContext.ROOT]
04-02-2020 15:09:23.762 [main] INFO  o.s.web.context.ContextLoader.prepareWebApplicationContext - Root WebApplicationContext: initialization completed in 964 ms
04-02-2020 15:09:25.676 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:09:25.711 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:09:25.734 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:09:25.743 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:09:56.690 [main] DEBUG o.s.web.context.ContextLoader.prepareWebApplicationContext - Published root WebApplicationContext as ServletContext attribute with name [org.springframework.web.context.WebApplicationContext.ROOT]
04-02-2020 15:09:56.690 [main] INFO  o.s.web.context.ContextLoader.prepareWebApplicationContext - Root WebApplicationContext: initialization completed in 978 ms
04-02-2020 15:09:58.566 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:09:58.597 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:09:58.618 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:09:58.626 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:13:13.745 [main] DEBUG o.s.w.c.s.GenericWebApplicationContext.prepareRefresh - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@7ef2d7a6
04-02-2020 15:13:17.436 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:13:17.488 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:13:17.519 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:13:17.531 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:13:17.848 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:13:17.864 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:13:17.888 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:17.889 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5d72da0b]
04-02-2020 15:13:17.896 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<?> se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController.authenticate(se.kth.iv1201.recruitmentbackend.presentation.models.LoginForm) throws java.lang.Exception]
04-02-2020 15:13:17.918 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:17.945 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:13:18.129 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:13:18.130 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.130 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@6b26839d]
04-02-2020 15:13:18.130 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:13:18.132 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:18.132 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=test, email=finnsej@gmail.com, ssn=9443528491, username=hejaaar, (truncated)...]
04-02-2020 15:13:18.141 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:13:18.142 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.142 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@157e0f6b]
04-02-2020 15:13:18.142 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given ssn already exists!]
04-02-2020 15:13:18.160 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:18.160 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:13:18.161 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.161 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5d414943]
04-02-2020 15:13:18.161 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController.registerPerson(se.kth.iv1201.recruitmentbackend.presentation.dto.PersonDTO,javax.servlet.http.HttpServletRequest)]
04-02-2020 15:13:18.168 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:18.169 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:13:18.174 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:13:18.175 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.175 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@71dac63f]
04-02-2020 15:13:18.176 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:13:18.177 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:18.177 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testar, lastName=testars, email=testay@gmail.com, ssn=9563258789, username=hejaa (truncated)...]
04-02-2020 15:13:18.182 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:13:18.183 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.183 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@58e0f079]
04-02-2020 15:13:18.184 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given email already exists!]
04-02-2020 15:13:18.190 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:18.190 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:13:18.195 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:13:18.195 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.195 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@4ac1544f]
04-02-2020 15:13:18.196 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:13:18.197 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:18.197 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=testars, email=testayssss@gmail.com, ssn=9494256712, username=he (truncated)...]
04-02-2020 15:13:18.201 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:13:18.201 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.202 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@605c2b9f]
04-02-2020 15:13:18.203 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:13:18.208 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:13:18.209 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=test, lastName=testar, email=testis@gmail.com, ssn=9403128991, username=Testis,  (truncated)...]
04-02-2020 15:13:18.212 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:13:18.213 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:13:18.213 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@38c9e937]
04-02-2020 15:13:18.213 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:13:18.218 [SpringContextShutdownHook] DEBUG o.s.w.c.s.GenericWebApplicationContext.doClose - Closing org.springframework.web.context.support.GenericWebApplicationContext@7ef2d7a6, started on Tue Feb 04 15:13:13 CET 2020
04-02-2020 15:13:58.713 [main] DEBUG o.s.w.c.s.GenericWebApplicationContext.prepareRefresh - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@3044e9c7
04-02-2020 15:14:02.760 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:14:02.823 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:14:02.858 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:14:02.874 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:14:03.314 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.396 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:14:03.587 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:14:03.596 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.596 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5bbaaf17]
04-02-2020 15:14:03.601 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:14:03.606 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.606 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=test, email=finnsej@gmail.com, ssn=9443528491, username=hejaaar, (truncated)...]
04-02-2020 15:14:03.616 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:14:03.616 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.617 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@65145fb7]
04-02-2020 15:14:03.617 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given ssn already exists!]
04-02-2020 15:14:03.637 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.638 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:14:03.638 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.639 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@3d94b49d]
04-02-2020 15:14:03.639 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController.registerPerson(se.kth.iv1201.recruitmentbackend.presentation.dto.PersonDTO,javax.servlet.http.HttpServletRequest)]
04-02-2020 15:14:03.645 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.646 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:14:03.650 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:14:03.650 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.650 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@70a984c5]
04-02-2020 15:14:03.651 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:14:03.652 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.652 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testar, lastName=testars, email=testay@gmail.com, ssn=9563258789, username=hejaa (truncated)...]
04-02-2020 15:14:03.656 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:14:03.657 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.657 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5a63de07]
04-02-2020 15:14:03.657 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given email already exists!]
04-02-2020 15:14:03.663 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.664 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:14:03.668 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:14:03.668 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.669 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@1676e501]
04-02-2020 15:14:03.669 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:14:03.670 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.671 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=testars, email=testayssss@gmail.com, ssn=9494256712, username=he (truncated)...]
04-02-2020 15:14:03.674 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:14:03.675 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.675 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@6f999cf4]
04-02-2020 15:14:03.675 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:14:03.681 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:14:03.682 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=test, lastName=testar, email=testis@gmail.com, ssn=9403128991, username=Testis,  (truncated)...]
04-02-2020 15:14:03.686 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:14:03.686 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.687 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@4ec78008]
04-02-2020 15:14:03.687 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:14:03.700 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:14:03.701 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:14:03.702 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:14:03.702 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@21d30ba5]
04-02-2020 15:14:03.702 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<?> se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController.authenticate(se.kth.iv1201.recruitmentbackend.presentation.models.LoginForm) throws java.lang.Exception]
04-02-2020 15:14:03.708 [SpringContextShutdownHook] DEBUG o.s.w.c.s.GenericWebApplicationContext.doClose - Closing org.springframework.web.context.support.GenericWebApplicationContext@3044e9c7, started on Tue Feb 04 15:13:58 CET 2020
04-02-2020 15:14:56.524 [main] DEBUG o.s.w.c.s.GenericWebApplicationContext.prepareRefresh - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@41d7b27f
04-02-2020 15:15:00.221 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:15:00.274 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:15:00.305 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:15:00.329 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:15:00.666 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:00.724 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:15:00.921 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:00.931 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:00.932 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@76dc9569]
04-02-2020 15:15:00.937 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:15:00.943 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:00.944 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=test, email=finnsej@gmail.com, ssn=9443528491, username=hejaaar, (truncated)...]
04-02-2020 15:15:00.953 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:00.954 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:00.954 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@65145fb7]
04-02-2020 15:15:00.955 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given ssn already exists!]
04-02-2020 15:15:00.977 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:00.979 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:15:00.979 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:00.979 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@3d94b49d]
04-02-2020 15:15:00.980 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController.registerPerson(se.kth.iv1201.recruitmentbackend.presentation.dto.PersonDTO,javax.servlet.http.HttpServletRequest)]
04-02-2020 15:15:00.985 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:00.986 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:15:00.990 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:00.990 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:00.990 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@70a984c5]
04-02-2020 15:15:00.991 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:15:00.992 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:00.992 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testar, lastName=testars, email=testay@gmail.com, ssn=9563258789, username=hejaa (truncated)...]
04-02-2020 15:15:00.997 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:00.998 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:00.998 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5a63de07]
04-02-2020 15:15:00.998 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given email already exists!]
04-02-2020 15:15:01.005 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:01.006 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:15:01.010 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:01.011 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:01.011 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@1676e501]
04-02-2020 15:15:01.011 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:15:01.012 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:01.013 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=testars, email=testayssss@gmail.com, ssn=9494256712, username=he (truncated)...]
04-02-2020 15:15:01.017 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:01.017 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:01.018 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@6f999cf4]
04-02-2020 15:15:01.018 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:15:01.025 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:01.025 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=test, lastName=testar, email=testis@gmail.com, ssn=9403128991, username=Testis,  (truncated)...]
04-02-2020 15:15:01.030 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:01.030 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:01.031 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@4ec78008]
04-02-2020 15:15:01.031 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:15:01.043 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:15:01.044 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:15:01.045 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:01.045 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@21d30ba5]
04-02-2020 15:15:01.045 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<?> se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController.authenticate(se.kth.iv1201.recruitmentbackend.presentation.models.LoginForm) throws java.lang.Exception]
04-02-2020 15:15:01.051 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:15:01.052 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=hellos, lastName=helloy, email=hello@gmail.com, ssn=9443578491, username=hello,  (truncated)...]
04-02-2020 15:15:01.055 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:15:01.055 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:01.056 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@7a7698f4]
04-02-2020 15:15:01.056 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:15:01.057 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:15:01.058 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [LoginForm(username=hello, password=då)]
04-02-2020 15:15:02.124 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:15:02.124 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.traceDebug - Writing [LoginResponse(jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZWxsbyIsInJvbGVzIjoiW1JPTEVfQVBQTElDQU5UXSIs (truncated)...]
04-02-2020 15:15:02.132 [SpringContextShutdownHook] DEBUG o.s.w.c.s.GenericWebApplicationContext.doClose - Closing org.springframework.web.context.support.GenericWebApplicationContext@41d7b27f, started on Tue Feb 04 15:14:56 CET 2020
04-02-2020 15:19:30.388 [main] DEBUG o.s.w.c.s.GenericWebApplicationContext.prepareRefresh - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@41d7b27f
04-02-2020 15:19:34.170 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:19:34.223 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:19:34.253 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:19:34.265 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:19:34.628 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.679 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:19:34.860 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.869 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.869 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@6870e039]
04-02-2020 15:19:34.875 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:19:34.879 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.880 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=test, email=finnsej@gmail.com, ssn=9443528491, username=hejaaar, (truncated)...]
04-02-2020 15:19:34.887 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.888 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.888 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@642693c2]
04-02-2020 15:19:34.889 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given ssn already exists!]
04-02-2020 15:19:34.911 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.912 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:19:34.913 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.913 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5c39da9e]
04-02-2020 15:19:34.913 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController.registerPerson(se.kth.iv1201.recruitmentbackend.presentation.dto.PersonDTO,javax.servlet.http.HttpServletRequest)]
04-02-2020 15:19:34.920 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.920 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:19:34.924 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.925 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.925 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@3d94b49d]
04-02-2020 15:19:34.925 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:19:34.926 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.927 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testar, lastName=testars, email=testay@gmail.com, ssn=9563258789, username=hejaa (truncated)...]
04-02-2020 15:19:34.932 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.932 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.933 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@30dabb23]
04-02-2020 15:19:34.933 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given email already exists!]
04-02-2020 15:19:34.939 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.940 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:19:34.945 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.946 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.946 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@68596992]
04-02-2020 15:19:34.946 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:19:34.947 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.948 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=testars, email=testayssss@gmail.com, ssn=9494256712, username=he (truncated)...]
04-02-2020 15:19:34.953 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.953 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.954 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@f1e8753]
04-02-2020 15:19:34.954 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:19:34.961 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.962 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=test, lastName=testar, email=testis@gmail.com, ssn=9403128991, username=Testis,  (truncated)...]
04-02-2020 15:19:34.965 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.966 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.966 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@7892635c]
04-02-2020 15:19:34.966 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:19:34.978 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:19:34.979 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:19:34.980 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.980 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@3670af2b]
04-02-2020 15:19:34.980 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<?> se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController.authenticate(se.kth.iv1201.recruitmentbackend.presentation.models.LoginForm) throws java.lang.Exception]
04-02-2020 15:19:34.986 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:19:34.987 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=hellos, lastName=helloy, email=hello@gmail.com, ssn=9443578491, username=hello,  (truncated)...]
04-02-2020 15:19:34.991 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:19:34.991 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:34.992 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@1b68e626]
04-02-2020 15:19:34.992 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:19:34.993 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:19:34.994 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [LoginForm(username=hello, password=då)]
04-02-2020 15:19:36.083 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:19:36.083 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.traceDebug - Writing [LoginResponse(jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZWxsbyIsInJvbGVzIjoiW1JPTEVfQVBQTElDQU5UXSIs (truncated)...]
04-02-2020 15:19:36.091 [SpringContextShutdownHook] DEBUG o.s.w.c.s.GenericWebApplicationContext.doClose - Closing org.springframework.web.context.support.GenericWebApplicationContext@41d7b27f, started on Tue Feb 04 15:19:30 CET 2020
04-02-2020 15:27:47.385 [main] DEBUG o.s.w.c.s.GenericWebApplicationContext.prepareRefresh - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@29b732a2
04-02-2020 15:27:51.065 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:27:51.123 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:27:51.151 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:27:51.164 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:27:51.503 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:27:51.519 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:27:51.545 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:27:51.545 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5c7876e1]
04-02-2020 15:27:51.554 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<?> se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController.authenticate(se.kth.iv1201.recruitmentbackend.presentation.models.LoginForm) throws java.lang.Exception]
04-02-2020 15:27:51.577 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:27:51.601 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:27:51.792 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:27:51.793 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:27:51.793 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@4beec7a1]
04-02-2020 15:27:51.793 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:27:51.795 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:27:51.796 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [LoginForm(username=heja, password=då)]
04-02-2020 15:27:52.845 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:27:52.845 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.traceDebug - Writing [LoginResponse(jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZWphIiwicm9sZXMiOiJbUk9MRV9BUFBMSUNBTlRdIiwi (truncated)...]
04-02-2020 15:27:52.854 [SpringContextShutdownHook] DEBUG o.s.w.c.s.GenericWebApplicationContext.doClose - Closing org.springframework.web.context.support.GenericWebApplicationContext@29b732a2, started on Tue Feb 04 15:27:47 CET 2020
04-02-2020 15:35:35.685 [main] DEBUG o.s.w.c.s.GenericWebApplicationContext.prepareRefresh - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@41a6d121
04-02-2020 15:35:39.490 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:35:39.544 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:35:39.574 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:35:39.587 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:35:39.930 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:39.994 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:35:40.183 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:35:40.193 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.193 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@34986491]
04-02-2020 15:35:40.199 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:35:40.203 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:40.204 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=test, email=finnsej@gmail.com, ssn=9443528491, username=hejaaar, (truncated)...]
04-02-2020 15:35:40.213 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:35:40.214 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.214 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@27e42fe8]
04-02-2020 15:35:40.214 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given ssn already exists!]
04-02-2020 15:35:40.236 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:40.237 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:35:40.238 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.238 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@4a648b35]
04-02-2020 15:35:40.238 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController.registerPerson(se.kth.iv1201.recruitmentbackend.presentation.dto.PersonDTO,javax.servlet.http.HttpServletRequest)]
04-02-2020 15:35:40.245 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:40.246 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=test, lastName=testar, email=testis@gmail.com, ssn=9403128991, username=Testis,  (truncated)...]
04-02-2020 15:35:40.250 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:35:40.250 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.250 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@6add8aac]
04-02-2020 15:35:40.251 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:35:40.259 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:40.260 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:35:40.264 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:35:40.265 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.265 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5a63de07]
04-02-2020 15:35:40.266 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:35:40.267 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:40.268 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testar, lastName=testars, email=testay@gmail.com, ssn=9563258789, username=hejaa (truncated)...]
04-02-2020 15:35:40.273 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:35:40.274 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.274 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@1f26bd62]
04-02-2020 15:35:40.274 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given email already exists!]
04-02-2020 15:35:40.281 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:40.282 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:35:40.285 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:35:40.286 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.286 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@79c9a128]
04-02-2020 15:35:40.286 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:35:40.287 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:35:40.288 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=testars, email=testayssss@gmail.com, ssn=9494256712, username=he (truncated)...]
04-02-2020 15:35:40.292 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:35:40.293 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:35:40.293 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@4ec78008]
04-02-2020 15:35:40.293 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:35:40.303 [SpringContextShutdownHook] DEBUG o.s.w.c.s.GenericWebApplicationContext.doClose - Closing org.springframework.web.context.support.GenericWebApplicationContext@41a6d121, started on Tue Feb 04 15:35:35 CET 2020
04-02-2020 15:38:38.939 [main] DEBUG o.s.w.c.s.GenericWebApplicationContext.prepareRefresh - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@41d7b27f
04-02-2020 15:38:42.600 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter.initControllerAdviceCache - ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 RequestBodyAdvice, 1 ResponseBodyAdvice
04-02-2020 15:38:42.654 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.handlerMethodsInitialized - 6 mappings in 'requestMappingHandlerMapping'
04-02-2020 15:38:42.686 [main] DEBUG o.s.w.s.c.a.WebMvcConfigurer.addResourceHandlers - Default resource handling disabled
04-02-2020 15:38:42.699 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.initExceptionHandlerAdviceCache - ControllerAdvice beans: 2 @ExceptionHandler, 1 ResponseBodyAdvice
04-02-2020 15:38:43.069 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.125 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:38:43.319 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.329 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.330 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@5bbaaf17]
04-02-2020 15:38:43.335 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:38:43.339 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.340 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=test, email=finnsej@gmail.com, ssn=9443528491, username=hejaaar, (truncated)...]
04-02-2020 15:38:43.349 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.350 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.351 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@72499396]
04-02-2020 15:38:43.351 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given ssn already exists!]
04-02-2020 15:38:43.372 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.373 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:38:43.374 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.374 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@57573880]
04-02-2020 15:38:43.374 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public void se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController.registerPerson(se.kth.iv1201.recruitmentbackend.presentation.dto.PersonDTO,javax.servlet.http.HttpServletRequest)]
04-02-2020 15:38:43.381 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.382 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=test, lastName=testar, email=testis@gmail.com, ssn=9403128991, username=Testis,  (truncated)...]
04-02-2020 15:38:43.385 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.386 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.386 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@70a984c5]
04-02-2020 15:38:43.388 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:38:43.397 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.398 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:38:43.401 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.402 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.402 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@119de68f]
04-02-2020 15:38:43.403 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:38:43.404 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.405 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testar, lastName=testars, email=testay@gmail.com, ssn=9563258789, username=hejaa (truncated)...]
04-02-2020 15:38:43.410 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.410 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.410 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@6dacde96]
04-02-2020 15:38:43.411 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given email already exists!]
04-02-2020 15:38:43.417 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.417 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:38:43.421 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.422 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.422 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@388ad8aa]
04-02-2020 15:38:43.422 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:38:43.423 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.424 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testa, lastName=testars, email=testayssss@gmail.com, ssn=9494256712, username=he (truncated)...]
04-02-2020 15:38:43.428 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.428 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.428 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@4075c0d8]
04-02-2020 15:38:43.429 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:38:43.437 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:38:43.438 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#messageNotReadableExceptionHandler(HttpMessageNotReadableException)
04-02-2020 15:38:43.439 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.439 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@dd26290]
04-02-2020 15:38:43.439 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<?> se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController.authenticate(se.kth.iv1201.recruitmentbackend.presentation.models.LoginForm) throws java.lang.Exception]
04-02-2020 15:38:43.444 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.RecruitmentController#registerPerson(PersonDTO, HttpServletRequest)
04-02-2020 15:38:43.445 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [PersonDTO(firstName=testyy, lastName=testaryy, email=testay@gmail.com, ssn=9443528491, username=heja (truncated)...]
04-02-2020 15:38:43.448 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException - Using @ExceptionHandler se.kth.iv1201.recruitmentbackend.presentation.error.ExceptionHandlers#illegalTransactionExceptionHandler(IllegalTransactionException)
04-02-2020 15:38:43.449 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:43.449 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Writing [se.kth.iv1201.recruitmentbackend.presentation.error.ErrorResponse@35ab83a7]
04-02-2020 15:38:43.450 [main] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver.resolveException - Resolved [se.kth.iv1201.recruitmentbackend.application.exception.IllegalTransactionException: A person with the given username already exists!]
04-02-2020 15:38:43.450 [main] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping.getHandler - Mapped to se.kth.iv1201.recruitmentbackend.presentation.controller.AuthenticationController#authenticate(LoginForm)
04-02-2020 15:38:43.452 [main] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor.traceDebug - Read "application/json;charset=UTF-8" to [LoginForm(username=heja, password=då)]
04-02-2020 15:38:44.500 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.writeWithMessageConverters - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
04-02-2020 15:38:44.500 [main] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor.traceDebug - Writing [LoginResponse(jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZWphIiwicm9sZXMiOiJbUk9MRV9BUFBMSUNBTlRdIiwi (truncated)...]
04-02-2020 15:38:44.508 [SpringContextShutdownHook] DEBUG o.s.w.c.s.GenericWebApplicationContext.doClose - Closing org.springframework.web.context.support.GenericWebApplicationContext@41d7b27f, started on Tue Feb 04 15:38:38 CET 2020
